version: 2
jobs:
  build:
    docker:
      - image: devkitpro/devkita64
    steps:
      - checkout
      - run: sudo apt-get -y install zip
      - run: make
      - run: mkdir -p switch/tinfoil/
      - run: mkdir zip
      - run: cp tinfoil.nro switch/tinfoil/tinfoil.nro
      - run: cp tinfoil.nacp switch/tinfoil/tinfoil.nacp
      - run: zip -r zip/tinfoil_${CIRCLE_BUILD_NUM}.zip switch
      - store_artifacts:
          path: zip/
